# docker/nginx/Dockerfile
# context = docker/nginx/ → jadi COPY cukup pakai nama file langsung

FROM nginx:1.25-alpine

# Karena context = docker/nginx/, cukup COPY default.conf (tanpa path panjang)
COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/public

EXPOSE 80